// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(WordFinderContext))]
    [Migration("20201002221242_InitialCommit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DBEntities.Entities.Searches", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<string>("AlgorithmKey")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("CTS")
                        .HasColumnType("DATETIME");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<DateTime?>("MTS")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Matrix")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("UserName")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("WordStream")
                        .HasColumnType("VARCHAR(MAX)");

                    b.HasKey("Id");

                    b.ToTable("Searches","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
